version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: interview_db
    environment:
      POSTGRES_PASSWORD: mysecretpassword # *** PLEASE CHANGE THIS PASSWORD ***
      POSTGRES_DB: interview_prep_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d interview_prep_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
